### PR TITLE
Fixes to compile under linux

### PR DESCRIPTION
**Pull request by mingodad**
Hello !
Here are small fixes to compile under linux, sadly there was several white spaces at the end of line that my editor trimmed out.
Cheers !

### CODE REVIEW

**Comment by mingodad** [comment]
I found your project because I was looking for a FLTK terminal emulator, how hard do you think would be to make it a local terminal emulator ? I mean have a local shell.

**Comment by mingodad** [comment]
Ideally be able to add a local terminal to https://github.com/McNeight/FLDev and have a basic IDE easy to customize for specific purposes and also if possible using https://github.com/cyantreeguo/Fl_Scintilla.

**Comment by yongchaofan** [comment]
Thanks for the pull request, I am working on the next release, to improve vt100 escape sequence handling, will incorporate your fixes. 

I will also look into the possibility of making it a local shell.

**Comment by mingodad** [comment]
Also today I found this project that touch a related topic https://github.com/buserror/libmish.git

**Comment by yongchaofan** [comment]
local shell terminal function committed to master

**Comment by mingodad** [comment]
How to use the local shell terminal from the executable created ?
I compiled but could not find how to achieve it.

**Comment by yongchaofan** [comment]
enable "localedit" from options menu, then type shell name (e.g. /bin/sh) and press "enter".

I will add shell connection to the connect dialog today

Thanks,
Yongchao

**Comment by mingodad** [comment]
Thanks for reply !
I'm compiling with FLTK 1.4 and when I try to type anything a kind of "scroll window history"  appears and there is no way to escape it unless clicking again on the terminal and there is "small squares" for the "nl/cr" characters.
I'll try to look at it with a bit more detail, but it's getting pretty good !

**Comment by yongchaofan** [comment]
The scrolling history is part of the local edit feature, you can disable through options menu, or press Alt-E

Small squares at end of each line comes from the font used, try select a different font, consolas or lucida console works well.
Thanks,
Yongchao

**Comment by mingodad** [comment]
I did a look at the "small squares" problem and I remember having something like this before with FLTK and it was related to output "\r\n", and commenting the line shown bellow seems to eliminate the problem without any visible unexpected side effect when using the local shell:
```
@@ -535,7 +535,7 @@ void Fl_Term::append( const char *newtext, int len ){
 				else {	//LF and newline
 					cursor_x = line[cursor_y+1]	;
 					attr[cursor_x] = c_attr;
-					buff[cursor_x++] = 0x0a;
+					//buff[cursor_x++] = 0x0a;
 					next_line();
 				}
 				break;
```

**Comment by mingodad** [comment]
Also the makefile for linux still doesn't work out of the box because when cloning the repository there is not an `obj` folder and the make file **do not check for it** and create it if it doesn't exists.

**Comment by yongchaofan** [comment]
You can of course remove those "\r\n" from display buffer, that will remove the small squares. But that will also cause problems when you try to copy some text from the buffer

I have created the obj directory in the repository, trying to keep the Makefile simple, the test and create command doesn't work on all linux versions, doesn't work on macOS either

**Pull request merged**
